baseURL = "https://joogajonttu.github.io/Blogi/"
languageCode = "fi"
title = "Joogajonttu"

theme = "PaperMod"

paginate = 5

[params]
  showReadingTime = true
  showPostNavLinks = true
  showBreadCrumbs = true
  ShowShareButtons = true
  copyright = "© 2026 Joogajonttu"
  
[menu]
[[menu.main]]
name = "Etusivu"
url = "/"
weight = 1

[[menu.main]]
name = "Julkaisut"
url = "/julkaisut/"
weight = 2

[[menu.main]]
name = "Minusta"
url = "/minusta/"
weight = 3
