baseURL = "https://joogajonttu.github.io/Blogi/"
languageCode = "fi"
title = "Joogajonttu"

theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowShareButtons = true


[menu]

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 10
