baseURL = "https://joogajonttu.github.io/Blogi/"
languageCode = "fi"
title = "Joogajonttu"

theme = "PaperMod"

paginate = 5

[params]
  showReadingTime = true
  showPostNavLinks = true
  showBreadCrumbs = true
  ShowShareButtons = true
  hideFooter = "© 2026 Joogajonttu"

[menu]

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 10
